name: CI

on:
  push:
    branches: [test_ci]


jobs:
  display:
    runs-on: ubuntu-latest
    env:
      platform: Azure
      region: central
      profile_path: profile/
    steps:
      - name: Display custom environment variable
        if: ${{ env.platform== 'Azure' }}
        run:
          echo "The platform is ${{ env.platform }} "
          echo "The region is $region"
